apps/cart/urls.py
from django.conf.urls import url
from apps.cart.views import CartAddView,CartInfoView

urlpatterns = [
    url(r'^add$', CartAddView.as_view(),name='add'),# 购物车添加记录
    url(r'^$', CartInfoView.as_view(), name='show'), #购物车页面展示
]

apps/goods/urls.py
from django.conf.urls import url

from apps.goods.views import IndexView,DetailView,ListView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^goods/(?P<sku_id>\d+)$', DetailView.as_view(), name='detail'),#详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list')
]

apps/user/urls.py
from django.conf.urls import url
from apps.user.views import RegisterView, ActiveView, LoginView\
    , AddressView, LogoutView, UserOrderView,UserInfoView

urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),  # 注册
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 激活
    url(r'^login', LoginView.as_view(), name='login'),  #登录
    url(r'^logout', LogoutView.as_view(), name='logout'), #注销
    url(r'^address$', AddressView.as_view(), name='address'), #地址
    url(r'^order/(?P<page>(/d)*)$', UserOrderView.as_view(),name='order'),#订单信息
    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
]

dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('apps.user.urls', namespace='user')),  # 用户模块
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),  # 购物车模块
    url(r'^', include('apps.goods.urls', namespace='goods')),  # 商品模块
    url(r'^order/', include('apps.order.urls', namespace='order')),  # 订单模块
    url(r'^search/', include('haystack.urls')), #搜索引擎url
    url(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
# Create your views here.
from django_redis import get_redis_connection

from apps.goods.models import GoodsSKU


class CartAddView(View):
    '''购物车记录添加'''
    def post(self,requst):
        # 判断用户是否登录
        user = requst.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'message': '请先登录'})
        '''获取用户传递的参数'''
        sku_id = requst.POST.get('sku_id')
        count = requst.POST.get('count')
        # 参数校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 0,  'message': '参数不完整'})
        # 检验商品ID
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'message': '商品信息错误'})
        # 检验商品数量
        try:
            count=int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'message': '商品数量必须为数字'})
        # 业务处理，购物车记录添加
        # 获取redis链接
        conn = get_redis_connection('default')
        # 拼接key
        key = 'cart_%d'% user.id
        # hget(key, field)
        cart_count = conn.hget(key, sku_id)

        if cart_count:
            # 如果用户购物车已经添加过sku_id商品，购物车对应商品的数目需要累加
            count+=int(cart_count)
        # 检验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'message': '商品库存不足'})
        # 设置用户购物车中sku_id商品和数量
        # hset(key,field,value) 存在就修改，不存在就新增
        conn.hset(key,sku_id,count)
        # 获取用户购物车中商品的条目数
        cart_count = conn.hlen(key)
        # 返回应答
        return JsonResponse({'res': 5, 'cart_count': cart_count,'errmsg':'添加购物车成功'})

class CartInfoView(View):
    '''购物车页面展示'''
    def get(self,request):
        # 获取当前登录用户
        user = request.user
        # 从redis获取用户购物车数据
        conn = get_redis_connection('default')
        # 拼接key
        key = 'cart_%d'% user.id
        # hgetall(key),返回的是一个字典，键是商品ID，值是商品数量
        cart_dict = conn.hgetall(key)
        total_count = 0
        total_amount = 0
        #遍历获取购物车商品详细信息
        skus=[]
        for sku_id, count in cart_dict.items():
            # 根据sku_id取商品
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品小计
            amount = sku.price * int(count)
            # 给sku增加属性amount和count,分别保存用户购物车商品的小计和数量
            sku.amount = amount
            sku.count = count
            # 追加商品信息
            skus.append(sku)
            #累计计算用户购物车中商品总价格和总数量
            total_count += int(count)
            total_amount += amount
        # 组织模板上下文
        context={
            'skus': skus,
            'total_count': total_count,
            'total_amount': total_amount,
        }
        return render(request, 'cart.html', context)


templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{%  load static from staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题块 #}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	 {# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
                <div class="login_info fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					{#<a href="{% url 'user:order' 1 %}">我的订单</a>#}
				</div>

			</div>
		</div>
	</div>
{% endblock header_con %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body %}{% endblock body %}
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>

templates/base_detail_list.html
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in  types%}
                        <li><a href="{% url 'goods:list' type.id 1%}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
        {# 详情页 列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_no_cart.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block body %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}
{% endblock body %}

templates/base_user_center.html
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1ce %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心右侧内容块 #}
		{% block right_content %}{% endblock right_content %}
	</div>
{% endblock body %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品详情{% endblock %}
{% load static from staticfiles %}
{% block main_content %}
    <div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{%  url 'goods:list' sku.category.id 1 %}">{{ sku.category.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>
    <div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ MEDIA_URL }}{{ sku.image }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
            <div>
                <div>其他规格:</div>
                <div>
                    {% for sku in same_spu_skus %}
                        <a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a>
                    {% endfor %}
                </div>
            </div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" sku_id="{{ sku.id }}" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>
    <div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
                        <li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ MEDIA_URL }}{{ sku.image }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }} 元</div>
					</li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock main_content %}
{% block bottom %}
    	<div class="add_jump"></div>
{% endblock bottom %}

{% block bottomfiles %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
     // 计算商品总价
        function update_sku_amount() {
            // 获取商品的价格
            var price = $('.show_pirze').children('em').text();
            // 获取商品的数量
            var count = $('.num_show').val();
            // 计算商品的价格
            var amount = parseInt(count)*parseFloat(price);
            // 设置商品总价
            $('.total').children('em').text(amount.toFixed(2)+'元');
        }

        // 商品数目的增加
        $('.add').click(function () {
            // 获取商品的数目
            var count = $('.num_show').val();
            // 加1
            count = parseInt(count) + 1;
            // 重新设置
            $('.num_show').val(count);
            // 更新商品总价
            update_sku_amount();
        });

        // 商品数目的减少
        $('.minus').click(function () {
            // 获取商品的数目
            var count = $('.num_show').val();
            // 减1
            count = parseInt(count) - 1;
            if (count <= 0) {
                count = 1;
            }
            // 重新设置
            $('.num_show').val(count);
            // 更新商品总价
            update_sku_amount();
        });

        // 商品数目手动输入
        $('.num_show').blur(function () {
            // 获取用户输入的商品的数目
            var count = $('.num_show').val();
            // 校验数据
            if (isNaN(count) || count.trim().length==0 || parseInt(count) <= 0){
                count = 1;
            }
            // 重新设置
            // 1.5
            count = parseInt(count);
            $('.num_show').val(count);
            // 更新商品总价
            update_sku_amount();
        })
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			//获取商品ID和数量
            var sku_id = $(this).attr('sku_id');
            var count = $('.num_show').val();

            //发起ajax post请求，访问/cart/add，传递参数：sku_id,count
            //组织参数
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            var csrftoken = getCookie('csrftoken');
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            var params = {
                'sku_id': sku_id,
                'count': count,
                'csrfmiddlewaretoken': csrftoken
            };
            $.post('/cart/add', params, function (data) {
                if(data.res==5){
                    //购物车记录添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车商品的条目数
                                $('#show_count').html(data.cart_count);
                            });

                    });
                }else {
                    alert('添加失败')
                }
            })
		})
	</script>
{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}天天生鲜 - 首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{# 网页主体内容块 #}
{% block body %}
    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    <div class="center_con clearfix">
		<ul class="subnav fl">
        {# 遍历展示商品分类信息 #}
            {% for type in types %}
            <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{type.name  }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
            {# 首页轮播图 #}
			<ul class="slide_pics">
                {% for foo in indexGoodsBanner %}
                <li><a href="#"><img src="{{ MEDIA_URL }}{{ foo.image }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {# 首页促销活动 #}
            {% for foo in indexPromotionBanner %}
            <a href="{{ foo.url }}"><img src="{{ MEDIA_URL }}{{foo.image  }}"></a>
            {% endfor %}
		</div>
	</div>
     {# 首页分类展示商品 #}
    {% for category in types %}
     <div class="list_model">

        <div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ category.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in category.title_banner %}
                    <a href="#">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>
        <div class="goods_con clearfix">

			<div class="goods_banner fl"><img src="{{ MEDIA_URL }}{{ category.image }}"></div>
			<ul class="goods_list fl">
            {# 遍历展示type种类在首页展示的图片商品的信息 #}
                {% for banner in category.img_banner%}
                    <li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %} }">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ MEDIA_URL }}{{ banner.sku.image }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				    </li>
                {% endfor %}



			</ul>
		</div>
    </div>
    {% endfor %}


{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock %}
{% block main_content %}
    <div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' type.id 1 %}">{{ type.name }}</a>
	</div>
    <div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
				    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ MEDIA_URL }}{{ sku.image }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

    <div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ MEDIA_URL }}{{ sku.image }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}元</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
            </ul>
            <div class="pagenation">
                {% if skus_page.has_previous  %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">&lt;上一页</a>
                {% endif %}
                {% for pindex in pages %}
				<a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" {% if pindex == skus_page.number %}class="active"{% endif %}>{{ pindex }}</a>
				{% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页&gt;</a>
                {% endif %}
			</div>
    </div>
</div>
{% endblock main_content %}

templates/login.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}天天生鲜-登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    {# 表单的action地址不设置时，表单提交时会向浏览器地址栏中的url地址发起提交 #}
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" value="{{ username }}" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    <p class="error_tip">{{ errmsg }}</p>>
{% endblock body %}

templates/register.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}天天生鲜-注册{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
                <form method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
                </form>
			</div>
             <p class="error_tip">{{ errmsg }}</p>
		</div>

	</div>

{% endblock body %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% load staticfiles from static %}
{% block page_title%}基本信息{% endblock page_title %}
{% block right_content %}
        <div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ address.receiver }}</li>
							<li><span>联系方式：</span>{{ address.phone }}</li>
							<li><span>联系地址：</span>{{ address.addr }}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for sku in skus %}
                            <li>
                                <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image }}"></a>
                                <h4><a href="{% url 'goods:detail' sku.id %}">大兴大棚草莓</a></h4>
                                <div class="operate">
                                    <span class="prize">{{ sku.price }}</span>
                                    <span class="unit">{{ sku.unite }}</span>
                                    <a href="#" class="add_goods" title="加入购物车"></a>
                                </div>
                            </li>
                                 {% empty %}
                            <li>暂无历史浏览记录</li>
                        {% endfor %}

			        </ul>
		        </div>
		</div>
{% endblock right_content %}